tickets/DM-32723
lsst-dmsst/DM_SP_study pull request #7
Opened 2023-05-20 03:15 UTC by MelissaGraham

2024-02-29 17:52 UTC, leannep requested changes

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +\subsection{Main Survey and Wide-Fast-Deep (WFD)}
```suggestion
\subsection{Main Survey including Wide-Fast-Deep (WFD)}
```

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +\subsection{Main Survey and Wide-Fast-Deep (WFD)}
Main Survey *and* Wide-Fast-Deep implies that WFD is not part of Main Survey.  You could also just title this section Main Survey.

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +Data from the Main Survey will be processed with regular (non-special) processing.
Add a forward reference to 2.5 Regular (non-special) processing here as this is the first time that this term is used and is then defined in the next section. Another possibility is to move this whole paragraph to the next section on "Special Processing" and not discuss processing in any of these sub-sections defining terminology

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +described in the Data Products Definitions Document
```suggestion
described in the Data Management Science Pipelines Design \citeds{LDM-151} that produces the data products described in the Data Products Definitions Document
```

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +(LSE-163) that are designed for, and will be applied to, the Main Survey's observations.
```suggestion
(\citeds{LSE-163}) that are designed for, and will be applied to, the Main Survey's observations.
```

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +(LSE-163) that are designed for, and will be applied to, the Main Survey's observations.
pipelines are described in LDM-151, the produced data products in LSE-163. Feel free to reword my suggestions.

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +(LSE-163) that are designed for, and will be applied to, the Main Survey's observations.
I wonder if "Standard Processing" would be a better term?  Special processing could be carried out regularly  ... regular is a quite overloaded term

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +\subsection{Special Programs}
I would move this sub-section to come before "\subsection{Regular (non-special) processing}" -- it follows on logically from "Main Survey".  I also would find it more logical to have "Non-Special Processing" follow directly on from "Special Processing"

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +or beyond the Main Survey footprint which have a distinct observing strategy from
```suggestion
or beyond the Main Survey footprint that have a distinct observing strategy from
```

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +or beyond the Main Survey footprint which have a distinct observing strategy from
(restrictive clause)

2024-02-29 17:52 UTC, leannep commented on sec_intro.tex
> +\subsection{Special Processing}
I think it would help to add an example to this of a special processing. DDFs are the obvious one; the different configuration of the pipelines for the different cadence of observations, etc

2024-02-29 17:52 UTC, leannep commented on sec_sci.tex
> +\textbf{Region Labels -- }
Can a visit have > 1 region label? e.g "WFD, Elias-S1"? If so, this is not clear in this wording

2024-02-29 17:52 UTC, leannep commented on sec_sci.tex
> +or where doing so would compromise the Main Survey data products (e.g., introduce non-uniformity).
```suggestion
or where doing so would compromise the Main Survey data products (e.g., introduce additional non-uniformity beyond what would be expected based on the survey strategy).
```

2024-02-29 17:52 UTC, leannep commented on sec_sci.tex
> +or where doing so would compromise the Main Survey data products (e.g., introduce non-uniformity).
... or something to this effect. No survey is ever completely uniform and with rolling cadence potentially introducing an additional degree of non-uniformity, I want to be careful with our wording. Special processing should not be seen as a means to create additional data products to get around the inherent  non-uniformity of the survey

2024-02-29 17:52 UTC, leannep commented on sec_sci.tex
> +observign mode label.
```suggestion
observing mode label. 
```

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +minimum exposure time is 1 second (stretch goal: 0.1 seconds\footnote{A short-exposure survey
```suggestion
minimum exposure time of 1 second (stretch goal: 0.1 seconds\footnote{A short-exposure survey 
```

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +Special Programs which require the \emph{exact same} field pointing and
```suggestion
Special Programs that require the \emph{exact same} field pointing and 
```

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +Special Programs which require the \emph{exact same} field pointing and
(restrictive clause)

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +Special Programs which use very short ($<$2 sec) exposures
```suggestion
Special Programs that use very short ($<$2 sec) exposures 
```

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +Special Programs which use very short ($<$2 sec) exposures
(restrictive clause)

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +For Special Programs which obtain images with very bright sky backgrounds
```suggestion
For Special Programs that obtain images with very bright sky backgrounds
```

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +Data Management and System Performance teams.
```suggestion
Data Management and System Performance departments in Rubin Operations.
```

2024-02-29 17:52 UTC, leannep commented on sec_proc.tex
> +Options for RDM to process TOO observations, especially during the first year of Operations
```suggestion
Options for Data Management to process TOO observations, especially during the first year of Operations 
```

2024-02-29 17:52 UTC, leannep commented on ap_procbounds.tex
> +\item \bf{Short or long exposures.} Very short ($<$2 sec) exposures could be difficult to
```suggestion
\item \textbf{Short or long exposures.} Very short ($<$2 sec) exposures could be difficult to 
```

2024-02-29 17:52 UTC, leannep commented on ap_procbounds.tex
> +\item \bf{Bright backgrounds (twilight).} It is currently unclear whether images with very
```suggestion
\item \textbf{Bright backgrounds (twilight).} It is currently unclear whether images with very 
```

2024-02-29 17:52 UTC, leannep commented on ap_procbounds.tex
> +\item \bf{Non-sidereal tracking.} The full reduction and calibration of images obtained
```suggestion
\item \textbf{Non-sidereal tracking.} The full reduction and calibration of images obtained 
```

2024-02-29 17:52 UTC, leannep commented on ap_procbounds.tex
> +\item \bf{Non-sidereal tracking.} The full reduction and calibration of images obtained
These rendered with the whole sentence in bold

2024-03-01 03:06 UTC, MelissaGraham commented on sec_intro.tex
> +(LSE-163) that are designed for, and will be applied to, the Main Survey's observations.
I agree, "standard processing" is more appropriate. "Regular" was meant in the "normal" or "not-special" sense, but "regular" carries a cadence implication I hadn't thought about. I'll make the change.

2024-03-01 03:11 UTC, MelissaGraham commented on sec_intro.tex
> +\subsection{Special Programs}
swapped the order

2024-03-01 03:16 UTC, MelissaGraham commented on sec_intro.tex
> +\subsection{Special Processing}
add a sentence with examples and a reference to section 4.3 where there are more examples

2024-03-01 03:25 UTC, MelissaGraham commented on sec_sci.tex
> +\textbf{Region Labels -- }
clarified yes, regions will overlap

2024-03-01 03:28 UTC, MelissaGraham commented on sec_intro.tex
> +Data from the Main Survey will be processed with regular (non-special) processing.
added forward reference

2024-03-01 03:57 UTC, MelissaGraham commented
@leannep thank you for the review -- implemented every suggestion, all made sense and helpful and good. merging now...

2024-03-01 03:58 UTC, merged